// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/21/2026, 7:26:39 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/mac/Desktop/commonwealth/commomwealth/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/commonwealth/commomwealth/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/commonwealth/commomwealth/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/commonwealth/commomwealth/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/commonwealth/commomwealth/plugins/**/*.{js,ts,mjs}","/Users/mac/Desktop/commonwealth/commomwealth/composables/**/*.{js,ts,mjs}","/Users/mac/Desktop/commonwealth/commomwealth/utils/**/*.{js,ts,mjs}","/Users/mac/Desktop/commonwealth/commomwealth/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/commonwealth/commomwealth/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/commonwealth/commomwealth/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/commonwealth/commomwealth/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;